name: go_http
description: Reliable HTTP client for Dart — built for control, cancellation and consistency.
version: 0.2.2
homepage: https://github.com/atlet99/go_http
repository: https://github.com/atlet99/go_http
issue_tracker: https://github.com/atlet99/go_http/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.11.0
  crypto: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

topics:
  - http
  - networking
  - api
  - http-client
